### ISSUE TITLE
Add returns to constructors

### ISSUE THREAD

**Issue by moritzsternemann** [scotthovestadt/schema-object#79]
I have a project where I want to build an API wrapper using schema-object.
It would be very convenient if I could use sth like 
```
MyModel.query()
```
where query would return an array of results or a promise.

This is currently not possible because a constructor always returns a schema object.

**Comment by scotthovestadt** [comment]
@moritzsternemann 
You can assign custom methods to the SchemaObject instance:
https://github.com/scotthovestadt/schema-object#static-methods

Is that what you want?
